[codestyle]
workspace_dir='~/practice/atcoder/'
lang='python'
indent_type='tab' # 'tab' or 'space'
indent_width=2
template_file='~/practice/atcoder/templates/templates.py'

[etc]
download_without_login=true
save_no_session_cache=true
skip_existing_problems=false
in_example_format="in_{}.txt"
out_example_format="out_{}.txt"

# C++は以下
# [codestyle]
# workspace_dir='~/practice/atcoder/'
# lang='cpp'
# indent_type='tab' # 'tab' or 'space'
# indent_width=2
# template_file='~/practice/atcoder/templates/templates.cpp'

# [compiler]
# compile_command='g++ main.cpp -o main -std=c++17'
# compile_only_when_diff_detected=true

# [tester]
# compile_before_testing=true
# compile_only_when_diff_detected=true
# timeout_adjustment=1.2
