#!/usr/bin/env python3
import sys


def solve(N: int, S: str):
  first = last = target = -1
  for i in range(len(S)):
    if S[i] == "|" and first == -1:
      first = i
    elif S[i] == "|":
      last = i
    elif S[i] == "*":
      target = i

  if first < target < last:
    print("in")
  else:
    print("out")



# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
  def iterate_tokens():
    for line in sys.stdin:
      for word in line.split():
        yield word
  tokens = iterate_tokens()
  N = int(next(tokens))  # type: int
  S = next(tokens)  # type: str
  solve(N, S)

if __name__ == '__main__':
  main()
