#!/usr/bin/env python3
import sys

YES = "Yes"  # type: str
NO = "No"  # type: str


def solve(N: int, S: str):
#   「良」と評価した面接官が少なくとも 1 人いる
# 「不可」と評価した面接官がいない
  can = False
  for i in range(N):
    if S[i] == "o":
      can = True
    elif S[i] == "x":
      can = False
      break
  print(YES if can else NO)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
  def iterate_tokens():
    for line in sys.stdin:
      for word in line.split():
        yield word
  tokens = iterate_tokens()
  N = int(next(tokens))  # type: int
  S = next(tokens)  # type: str
  solve(N, S)

if __name__ == '__main__':
  main()
