#!/usr/bin/env python3
import sys


def solve(N: int, M: int, S: str, T: str):
  # S が T の接頭辞であり、かつ接尾辞でもある場合は 0
  if T.find(S) == 0:
    T2 = T[M-N:]
    if T2.find(S) == 0:
      print(0)
    # S が T の接頭辞であるが、接尾辞でない場合は 1
    else:
      print(1)
  # S が T の接尾辞であるが、接頭辞でない場合は 2
  elif T.find(S) == M - N:
    print(2)
  # S が T の接頭辞でも接尾辞でもない場合は 3
  else:
    print(3)
  return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
  def iterate_tokens():
    for line in sys.stdin:
      for word in line.split():
        yield word
  tokens = iterate_tokens()
  N = int(next(tokens))  # type: int
  M = int(next(tokens))  # type: int
  S = next(tokens)  # type: str
  T = next(tokens)  # type: str
  solve(N, M, S, T)

if __name__ == '__main__':
  main()
