#!/usr/bin/env python3
import sys

YES = "Yes"  # type: str
NO = "No"  # type: str


def solve(S: str):
				can =False
				b_index = []
				k_index = -1
				r_index = []
				for i in range(len(S)):
					if S[i] == "B":
						b_index.append(i)
					elif S[i] == "K":
						k_index = i
					elif S[i] == "R":
						r_index.append(i)

				if (b_index[0] % 2 != b_index[1] % 2) and (r_index[0] < k_index < r_index[1]):
					can = True

				print("Yes" if can else "No")


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
				def iterate_tokens():
								for line in sys.stdin:
												for word in line.split():
																yield word
				tokens = iterate_tokens()
				S = next(tokens)  # type: str
				solve(S)

if __name__ == '__main__':
				main()
